import spock.lang.Specification

class StringTasksSpec extends Specification {

    def "1: is lower case test"() {
        given:
        def result = StringTasks.isLowerCase(input)

        expect:
        result == expectedResult

        where:
        input                        ||   expectedResult
        null                         ||   false
        ""                           ||   false
        " "                          ||   false
        "123"                        ||   false
        "HelloWorld"                 ||   false
        "HELLOWORLD"                 ||   false
        "hello world"                ||   false
        "helloworld"                 ||   true
    }

    def "2: is upper case test"() {
        given:
        def result = StringTasks.isUpperCase(input)

        expect:
        result == expectedResult

        where:
        input                        ||   expectedResult
        null                         ||   false
        ""                           ||   false
        " "                          ||   false
        "123"                        ||   false
        "HelloWorld"                 ||   false
        "hello world"                ||   false
        "helloworld"                 ||   false
        "HELLOWORLD"                 ||   true
    }

    def "3: is camel case test"() {
        given:
        def result = StringTasks.isCamelCase(input)

        expect:
        result == expectedResult

        where:
        input                        ||   expectedResult
        null                         ||   false
        ""                           ||   false
        " "                          ||   false
        "123"                        ||   false
        "HelloWorld"                 ||   false
        "hello world"                ||   false
        "helloworld"                 ||   false
        "HELLOWORLD"                 ||   false
        "Helloworld"                 ||   true
    }

    def "4: is mixed case test"() {
        given:
        def result = StringTasks.isMixedCase(input)

        expect:
        result == expectedResult

        where:
        input                        ||   expectedResult
        null                         ||   false
        ""                           ||   false
        " "                          ||   false
        "123"                        ||   false
        "HelloWorld"                 ||   false
        "hello world"                ||   false
        "helloworld"                 ||   false
        "HELLOWORLD"                 ||   false
        "Helloworld"                 ||   false
        "HeLlOwOrLd"                 ||   true
    }

    def "5: is palindrome"() {
        given:
        def result = StringTasks.isPalindrome(input)

        expect:
        result == expectedResult

          where:
        input                        ||   expectedResult
        null                         ||   false
        ""                           ||   false
        "A nut for a jar of tuna"    ||   true
        "Stressed desserts"          ||   true
        "Madam, in Eden, Im Adam."   ||   true
        "Hello world!"               ||   false
        "Good morning"               ||   false

    }

    def "6: is strict palindrome"() {
        given:
        def result = StringTasks.isStrictPalindrome(input, isStrict)

        expect:
        result == expectedResult

        where:
        input                        ||   expectedResult  || isStrict
        null                         ||   false           || true
        null                         ||   false           || false
        ""                           ||   false           || true
        ""                           ||   false           || false
        "A nut for a jar of tuna"    ||   true            || false
        "A nut for a jar of tuna"    ||   false           || true
        "a nut for a jar of tuna"    ||   true            || true
        "Good morning"               ||   false           || true
        "Good morning"               ||   false           || false
    }

    def "7: is all characters paired"() {
        given:
        def result = StringTasks.isAllCharactersPaired(input)

        expect:
        result == expectedResult

        where:
        input            ||   expectedResult
        null             ||   false
        ""               ||   false
        "aaBBccDD55**"   ||   true
        "**"             ||   true
        "aaBBcC**hF"     ||   false
    }

    def "8: replace binary numbers test"() {
        given:
        def result = StringTasks.replaceBinaryNumbers(input)

        expect:
        result == expectedResult

        where:
        input            ||   expectedResult
        null             ||   null
        ""               ||   ""
        "23"             ||   "23"
        "1"              ||   "0"
        "0"              ||   "1"
        "1011"           ||   "0100"
        "abc01xyz000111" ||   "abc10xyz111000"
    }

    def "9: replace test"() {
        given:
        def result = StringTasks.replace(input, from as char, to as char)

        expect:
        result == expectedResult

        where:
        input               || from || to   || expectedResult
        "hello world"       || 'o'  || 'a'  || "hella warld"
        "do homework well"  || 'e'  || 'l'  || "do homlwork wlll"
        ""                  || 'o'  || 'a'  || ""
        "1 2 3 4 5 6"       || ' '  || '-'  || "1-2-3-4-5-6"
        "1 2 3 4 5 6"       || '-'  || '_'  || "1 2 3 4 5 6"
        null                || '-'  || '.'  || null
    }

    def "10: dragon curve test"() {
        given:
        def result = StringTasks.makeDragonCurve(n)

        expect:
        result == expectedResult

        where:
        n  || expectedResult
        0  || "R"
        1  || "RRL"
        2  || "RRLRRLL"
        3  || "RRLRRLLRRRLLRLL"
        13 || "RRLRRLLRRRLLRLLRRRLRRLLLRRLLRLLRRRLRRLLRRRLLRLLLRRLRRLLLRRLLRLLRRRLRRLLRRRLLRLLRRRLRRLLLRRLLRLLLRRLRRLLRRRLLRLLLRRLRRLLLRRLLRLLRRRLRRLLRRRLLRLLRRRLRRLLLRRLLRLLRRRLRRLLRRRLLRLLLRRLRRLLLRRLLRLLLRRLRRLLRRRLLRLLRRRLRRLLLRRLLRLLLRRLRRLLRRRLLRLLLRRLRRLLLRRLLRLLRRRLRRLLRRRLLRLLRRRLRRLLLRRLLRLLRRRLRRLLRRRLLRLLLRRLRRLLLRRLLRLLRRRLRRLLRRRLLRLLRRRLRRLLLRRLLRLLLRRLRRLLRRRLLRLLLRRLRRLLLRRLLRLLLRRLRRLLRRRLLRLLRRRLRRLLLRRLLRLLRRRLRRLLRRRLLRLLLRRLRRLLLRRLLRLLLRRLRRLLRRRLLRLLRRRLRRLLLRRLLRLLLRRLRRLLRRRLLRLLLRRLRRLLLRRLLRLLRRRLRRLLRRRLLRLLRRRLRRLLLRRLLRLLRRRLRRLLRRRLLRLLLRRLRRLLLRRLLRLLRRRLRRLLRRRLLRLLRRRLRRLLLRRLLRLLLRRLRRLLRRRLLRLLLRRLRRLLLRRLLRLLRRRLRRLLRRRLLRLLRRRLRRLLLRRLLRLLRRRLRRLLRRRLLRLLLRRLRRLLLRRLLRLLLRRLRRLLRRRLLRLLRRRLRRLLLRRLLRLLLRRLRRLLRRRLLRLLLRRLRRLLLRRLLRLLLRRLRRLLRRRLLRLLRRRLRRLLLRRLLRLLRRRLRRLLRRRLLRLLLRRLRRLLLRRLLRLLRRRLRRLLRRRLLRLLRRRLRRLLLRRLLRLLLRRLRRLLRRRLLRLLLRRLRRLLLRRLLRLLLRRLRRLLRRRLLRLLRRRLRRLLLRRLLRLLRRRLRRLLRRRLLRLLLRRLRRLLLRRLLRLLLRRLRRLLRRRLLRLLRRRLRRLLLRRLLRLLLRRLRRLLRRRLLRLLLRRLRRLLLRRLLRLLRRRLRRLLRRRLLRLLRRRLRRLLLRRLLRLLRRRLRRLLRRRLLRLLLRRLRRLLLRRLLRLLRRRLRRLLRRRLLRLLRRRLRRLLLRRLLRLLLRRLRRLLRRRLLRLLLRRLRRLLLRRLLRLLRRRLRRLLRRRLLRLLRRRLRRLLLRRLLRLLRRRLRRLLRRRLLRLLLRRLRRLLLRRLLRLLLRRLRRLLRRRLLRLLRRRLRRLLLRRLLRLLLRRLRRLLRRRLLRLLLRRLRRLLLRRLLRLLRRRLRRLLRRRLLRLLRRRLRRLLLRRLLRLLRRRLRRLLRRRLLRLLLRRLRRLLLRRLLRLLRRRLRRLLRRRLLRLLRRRLRRLLLRRLLRLLLRRLRRLLRRRLLRLLLRRLRRLLLRRLLRLLLRRLRRLLRRRLLRLLRRRLRRLLLRRLLRLLRRRLRRLLRRRLLRLLLRRLRRLLLRRLLRLLLRRLRRLLRRRLLRLLRRRLRRLLLRRLLRLLLRRLRRLLRRRLLRLLLRRLRRLLLRRLLRLLLRRLRRLLRRRLLRLLRRRLRRLLLRRLLRLLRRRLRRLLRRRLLRLLLRRLRRLLLRRLLRLLRRRLRRLLRRRLLRLLRRRLRRLLLRRLLRLLLRRLRRLLRRRLLRLLLRRLRRLLLRRLLRLLRRRLRRLLRRRLLRLLRRRLRRLLLRRLLRLLRRRLRRLLRRRLLRLLLRRLRRLLLRRLLRLLLRRLRRLLRRRLLRLLRRRLRRLLLRRLLRLLLRRLRRLLRRRLLRLLLRRLRRLLLRRLLRLLLRRLRRLLRRRLLRLLRRRLRRLLLRRLLRLLRRRLRRLLRRRLLRLLLRRLRRLLLRRLLRLLRRRLRRLLRRRLLRLLRRRLRRLLLRRLLRLLLRRLRRLLRRRLLRLLLRRLRRLLLRRLLRLLLRRLRRLLRRRLLRLLRRRLRRLLLRRLLRLLRRRLRRLLRRRLLRLLLRRLRRLLLRRLLRLLLRRLRRLLRRRLLRLLRRRLRRLLLRRLLRLLLRRLRRLLRRRLLRLLLRRLRRLLLRRLLRLLRRRLRRLLRRRLLRLLRRRLRRLLLRRLLRLLRRRLRRLLRRRLLRLLLRRLRRLLLRRLLRLLRRRLRRLLRRRLLRLLRRRLRRLLLRRLLRLLLRRLRRLLRRRLLRLLLRRLRRLLLRRLLRLLRRRLRRLLRRRLLRLLRRRLRRLLLRRLLRLLRRRLRRLLRRRLLRLLLRRLRRLLLRRLLRLLLRRLRRLLRRRLLRLLRRRLRRLLLRRLLRLLLRRLRRLLRRRLLRLLLRRLRRLLLRRLLRLLRRRLRRLLRRRLLRLLRRRLRRLLLRRLLRLLRRRLRRLLRRRLLRLLLRRLRRLLLRRLLRLLRRRLRRLLRRRLLRLLRRRLRRLLLRRLLRLLLRRLRRLLRRRLLRLLLRRLRRLLLRRLLRLLLRRLRRLLRRRLLRLLRRRLRRLLLRRLLRLLRRRLRRLLRRRLLRLLLRRLRRLLLRRLLRLLLRRLRRLLRRRLLRLLRRRLRRLLLRRLLRLLLRRLRRLLRRRLLRLLLRRLRRLLLRRLLRLLRRRLRRLLRRRLLRLLRRRLRRLLLRRLLRLLRRRLRRLLRRRLLRLLLRRLRRLLLRRLLRLLRRRLRRLLRRRLLRLLRRRLRRLLLRRLLRLLLRRLRRLLRRRLLRLLLRRLRRLLLRRLLRLLRRRLRRLLRRRLLRLLRRRLRRLLLRRLLRLLRRRLRRLLRRRLLRLLLRRLRRLLLRRLLRLLLRRLRRLLRRRLLRLLRRRLRRLLLRRLLRLLLRRLRRLLRRRLLRLLLRRLRRLLLRRLLRLLLRRLRRLLRRRLLRLLRRRLRRLLLRRLLRLLRRRLRRLLRRRLLRLLLRRLRRLLLRRLLRLLRRRLRRLLRRRLLRLLRRRLRRLLLRRLLRLLLRRLRRLLRRRLLRLLLRRLRRLLLRRLLRLLLRRLRRLLRRRLLRLLRRRLRRLLLRRLLRLLRRRLRRLLRRRLLRLLLRRLRRLLLRRLLRLLLRRLRRLLRRRLLRLLRRRLRRLLLRRLLRLLLRRLRRLLRRRLLRLLLRRLRRLLLRRLLRLLLRRLRRLLRRRLLRLLRRRLRRLLLRRLLRLLRRRLRRLLRRRLLRLLLRRLRRLLLRRLLRLLRRRLRRLLRRRLLRLLRRRLRRLLLRRLLRLLLRRLRRLLRRRLLRLLLRRLRRLLLRRLLRLLRRRLRRLLRRRLLRLLRRRLRRLLLRRLLRLLRRRLRRLLRRRLLRLLLRRLRRLLLRRLLRLLLRRLRRLLRRRLLRLLRRRLRRLLLRRLLRLLLRRLRRLLRRRLLRLLLRRLRRLLLRRLLRLLRRRLRRLLRRRLLRLLRRRLRRLLLRRLLRLLRRRLRRLLRRRLLRLLLRRLRRLLLRRLLRLLRRRLRRLLRRRLLRLLRRRLRRLLLRRLLRLLLRRLRRLLRRRLLRLLLRRLRRLLLRRLLRLLLRRLRRLLRRRLLRLLRRRLRRLLLRRLLRLLRRRLRRLLRRRLLRLLLRRLRRLLLRRLLRLLLRRLRRLLRRRLLRLLRRRLRRLLLRRLLRLLLRRLRRLLRRRLLRLLLRRLRRLLLRRLLRLLLRRLRRLLRRRLLRLLRRRLRRLLLRRLLRLLRRRLRRLLRRRLLRLLLRRLRRLLLRRLLRLLRRRLRRLLRRRLLRLLRRRLRRLLLRRLLRLLLRRLRRLLRRRLLRLLLRRLRRLLLRRLLRLLRRRLRRLLRRRLLRLLRRRLRRLLLRRLLRLLRRRLRRLLRRRLLRLLLRRLRRLLLRRLLRLLLRRLRRLLRRRLLRLLRRRLRRLLLRRLLRLLLRRLRRLLRRRLLRLLLRRLRRLLLRRLLRLLLRRLRRLLRRRLLRLLRRRLRRLLLRRLLRLLRRRLRRLLRRRLLRLLLRRLRRLLLRRLLRLLRRRLRRLLRRRLLRLLRRRLRRLLLRRLLRLLLRRLRRLLRRRLLRLLLRRLRRLLLRRLLRLLLRRLRRLLRRRLLRLLRRRLRRLLLRRLLRLLRRRLRRLLRRRLLRLLLRRLRRLLLRRLLRLLLRRLRRLLRRRLLRLLRRRLRRLLLRRLLRLLLRRLRRLLRRRLLRLLLRRLRRLLLRRLLRLLRRRLRRLLRRRLLRLLRRRLRRLLLRRLLRLLRRRLRRLLRRRLLRLLLRRLRRLLLRRLLRLLRRRLRRLLRRRLLRLLRRRLRRLLLRRLLRLLLRRLRRLLRRRLLRLLLRRLRRLLLRRLLRLLRRRLRRLLRRRLLRLLRRRLRRLLLRRLLRLLRRRLRRLLRRRLLRLLLRRLRRLLLRRLLRLLLRRLRRLLRRRLLRLLRRRLRRLLLRRLLRLLLRRLRRLLRRRLLRLLLRRLRRLLLRRLLRLLRRRLRRLLRRRLLRLLRRRLRRLLLRRLLRLLRRRLRRLLRRRLLRLLLRRLRRLLLRRLLRLLRRRLRRLLRRRLLRLLRRRLRRLLLRRLLRLLLRRLRRLLRRRLLRLLLRRLRRLLLRRLLRLLLRRLRRLLRRRLLRLLRRRLRRLLLRRLLRLLRRRLRRLLRRRLLRLLLRRLRRLLLRRLLRLLLRRLRRLLRRRLLRLLRRRLRRLLLRRLLRLLLRRLRRLLRRRLLRLLLRRLRRLLLRRLLRLLRRRLRRLLRRRLLRLLRRRLRRLLLRRLLRLLRRRLRRLLRRRLLRLLLRRLRRLLLRRLLRLLRRRLRRLLRRRLLRLLRRRLRRLLLRRLLRLLLRRLRRLLRRRLLRLLLRRLRRLLLRRLLRLLRRRLRRLLRRRLLRLLRRRLRRLLLRRLLRLLRRRLRRLLRRRLLRLLLRRLRRLLLRRLLRLLLRRLRRLLRRRLLRLLRRRLRRLLLRRLLRLLLRRLRRLLRRRLLRLLLRRLRRLLLRRLLRLLLRRLRRLLRRRLLRLLRRRLRRLLLRRLLRLLRRRLRRLLRRRLLRLLLRRLRRLLLRRLLRLLRRRLRRLLRRRLLRLLRRRLRRLLLRRLLRLLLRRLRRLLRRRLLRLLLRRLRRLLLRRLLRLLLRRLRRLLRRRLLRLLRRRLRRLLLRRLLRLLRRRLRRLLRRRLLRLLLRRLRRLLLRRLLRLLLRRLRRLLRRRLLRLLRRRLRRLLLRRLLRLLLRRLRRLLRRRLLRLLLRRLRRLLLRRLLRLLRRRLRRLLRRRLLRLLRRRLRRLLLRRLLRLLRRRLRRLLRRRLLRLLLRRLRRLLLRRLLRLLRRRLRRLLRRRLLRLLRRRLRRLLLRRLLRLLLRRLRRLLRRRLLRLLLRRLRRLLLRRLLRLLRRRLRRLLRRRLLRLLRRRLRRLLLRRLLRLLRRRLRRLLRRRLLRLLLRRLRRLLLRRLLRLLLRRLRRLLRRRLLRLLRRRLRRLLLRRLLRLLLRRLRRLLRRRLLRLLLRRLRRLLLRRLLRLLRRRLRRLLRRRLLRLLRRRLRRLLLRRLLRLLRRRLRRLLRRRLLRLLLRRLRRLLLRRLLRLLRRRLRRLLRRRLLRLLRRRLRRLLLRRLLRLLLRRLRRLLRRRLLRLLLRRLRRLLLRRLLRLLLRRLRRLLRRRLLRLLRRRLRRLLLRRLLRLLRRRLRRLLRRRLLRLLLRRLRRLLLRRLLRLLLRRLRRLLRRRLLRLLRRRLRRLLLRRLLRLLLRRLRRLLRRRLLRLLLRRLRRLLLRRLLRLLLRRLRRLLRRRLLRLLRRRLRRLLLRRLLRLLRRRLRRLLRRRLLRLLLRRLRRLLLRRLLRLLRRRLRRLLRRRLLRLLRRRLRRLLLRRLLRLLLRRLRRLLRRRLLRLLLRRLRRLLLRRLLRLLRRRLRRLLRRRLLRLLRRRLRRLLLRRLLRLLRRRLRRLLRRRLLRLLLRRLRRLLLRRLLRLLLRRLRRLLRRRLLRLLRRRLRRLLLRRLLRLLLRRLRRLLRRRLLRLLLRRLRRLLLRRLLRLLLRRLRRLLRRRLLRLLRRRLRRLLLRRLLRLLRRRLRRLLRRRLLRLLLRRLRRLLLRRLLRLLRRRLRRLLRRRLLRLLRRRLRRLLLRRLLRLLLRRLRRLLRRRLLRLLLRRLRRLLLRRLLRLLLRRLRRLLRRRLLRLLRRRLRRLLLRRLLRLLRRRLRRLLRRRLLRLLLRRLRRLLLRRLLRLLLRRLRRLLRRRLLRLLRRRLRRLLLRRLLRLLLRRLRRLLRRRLLRLLLRRLRRLLLRRLLRLLLRRLRRLLRRRLLRLLRRRLRRLLLRRLLRLLRRRLRRLLRRRLLRLLLRRLRRLLLRRLLRLLRRRLRRLLRRRLLRLLRRRLRRLLLRRLLRLLLRRLRRLLRRRLLRLLLRRLRRLLLRRLLRLLRRRLRRLLRRRLLRLLRRRLRRLLLRRLLRLLRRRLRRLLRRRLLRLLLRRLRRLLLRRLLRLLLRRLRRLLRRRLLRLLRRRLRRLLLRRLLRLLLRRLRRLLRRRLLRLLLRRLRRLLLRRLLRLLRRRLRRLLRRRLLRLLRRRLRRLLLRRLLRLLRRRLRRLLRRRLLRLLLRRLRRLLLRRLLRLLRRRLRRLLRRRLLRLLRRRLRRLLLRRLLRLLLRRLRRLLRRRLLRLLLRRLRRLLLRRLLRLLLRRLRRLLRRRLLRLLRRRLRRLLLRRLLRLLRRRLRRLLRRRLLRLLLRRLRRLLLRRLLRLLLRRLRRLLRRRLLRLLRRRLRRLLLRRLLRLLLRRLRRLLRRRLLRLLLRRLRRLLLRRLLRLLRRRLRRLLRRRLLRLLRRRLRRLLLRRLLRLLRRRLRRLLRRRLLRLLLRRLRRLLLRRLLRLLRRRLRRLLRRRLLRLLRRRLRRLLLRRLLRLLLRRLRRLLRRRLLRLLLRRLRRLLLRRLLRLLRRRLRRLLRRRLLRLLRRRLRRLLLRRLLRLLRRRLRRLLRRRLLRLLLRRLRRLLLRRLLRLLLRRLRRLLRRRLLRLLRRRLRRLLLRRLLRLLLRRLRRLLRRRLLRLLLRRLRRLLLRRLLRLLLRRLRRLLRRRLLRLLRRRLRRLLLRRLLRLLRRRLRRLLRRRLLRLLLRRLRRLLLRRLLRLLRRRLRRLLRRRLLRLLRRRLRRLLLRRLLRLLLRRLRRLLRRRLLRLLLRRLRRLLLRRLLRLLLRRLRRLLRRRLLRLLRRRLRRLLLRRLLRLLRRRLRRLLRRRLLRLLLRRLRRLLLRRLLRLLLRRLRRLLRRRLLRLLRRRLRRLLLRRLLRLLLRRLRRLLRRRLLRLLLRRLRRLLLRRLLRLLLRRLRRLLRRRLLRLLRRRLRRLLLRRLLRLLRRRLRRLLRRRLLRLLLRRLRRLLLRRLLRLLRRRLRRLLRRRLLRLLRRRLRRLLLRRLLRLLLRRLRRLLRRRLLRLLLRRLRRLLLRRLLRLLRRRLRRLLRRRLLRLLRRRLRRLLLRRLLRLLRRRLRRLLRRRLLRLLLRRLRRLLLRRLLRLLLRRLRRLLRRRLLRLLRRRLRRLLLRRLLRLLLRRLRRLLRRRLLRLLLRRLRRLLLRRLLRLLRRRLRRLLRRRLLRLLRRRLRRLLLRRLLRLLRRRLRRLLRRRLLRLLLRRLRRLLLRRLLRLLRRRLRRLLRRRLLRLLRRRLRRLLLRRLLRLLLRRLRRLLRRRLLRLLLRRLRRLLLRRLLRLLLRRLRRLLRRRLLRLLRRRLRRLLLRRLLRLLRRRLRRLLRRRLLRLLLRRLRRLLLRRLLRLLLRRLRRLLRRRLLRLLRRRLRRLLLRRLLRLLLRRLRRLLRRRLLRLLLRRLRRLLLRRLLRLLLRRLRRLLRRRLLRLLRRRLRRLLLRRLLRLLRRRLRRLLRRRLLRLLLRRLRRLLLRRLLRLLRRRLRRLLRRRLLRLLRRRLRRLLLRRLLRLLLRRLRRLLRRRLLRLLLRRLRRLLLRRLLRLLRRRLRRLLRRRLLRLLRRRLRRLLLRRLLRLLRRRLRRLLRRRLLRLLLRRLRRLLLRRLLRLLLRRLRRLLRRRLLRLLRRRLRRLLLRRLLRLLLRRLRRLLRRRLLRLLLRRLRRLLLRRLLRLLLRRLRRLLRRRLLRLLRRRLRRLLLRRLLRLLRRRLRRLLRRRLLRLLLRRLRRLLLRRLLRLLRRRLRRLLRRRLLRLLRRRLRRLLLRRLLRLLLRRLRRLLRRRLLRLLLRRLRRLLLRRLLRLLLRRLRRLLRRRLLRLLRRRLRRLLLRRLLRLLRRRLRRLLRRRLLRLLLRRLRRLLLRRLLRLLLRRLRRLLRRRLLRLLRRRLRRLLLRRLLRLLLRRLRRLLRRRLLRLLLRRLRRLLLRRLLRLLRRRLRRLLRRRLLRLLRRRLRRLLLRRLLRLLRRRLRRLLRRRLLRLLLRRLRRLLLRRLLRLLRRRLRRLLRRRLLRLLRRRLRRLLLRRLLRLLLRRLRRLLRRRLLRLLLRRLRRLLLRRLLRLLRRRLRRLLRRRLLRLLRRRLRRLLLRRLLRLLRRRLRRLLRRRLLRLLLRRLRRLLLRRLLRLLLRRLRRLLRRRLLRLLRRRLRRLLLRRLLRLLLRRLRRLLRRRLLRLLLRRLRRLLLRRLLRLLRRRLRRLLRRRLLRLLRRRLRRLLLRRLLRLLRRRLRRLLRRRLLRLLLRRLRRLLLRRLLRLLRRRLRRLLRRRLLRLLRRRLRRLLLRRLLRLLLRRLRRLLRRRLLRLLLRRLRRLLLRRLLRLLLRRLRRLLRRRLLRLLRRRLRRLLLRRLLRLLRRRLRRLLRRRLLRLLLRRLRRLLLRRLLRLLLRRLRRLLRRRLLRLLRRRLRRLLLRRLLRLLLRRLRRLLRRRLLRLLLRRLRRLLLRRLLRLLRRRLRRLLRRRLLRLLRRRLRRLLLRRLLRLLRRRLRRLLRRRLLRLLLRRLRRLLLRRLLRLLRRRLRRLLRRRLLRLLRRRLRRLLLRRLLRLLLRRLRRLLRRRLLRLLLRRLRRLLLRRLLRLLRRRLRRLLRRRLLRLLRRRLRRLLLRRLLRLLRRRLRRLLRRRLLRLLLRRLRRLLLRRLLRLLLRRLRRLLRRRLLRLLRRRLRRLLLRRLLRLLLRRLRRLLRRRLLRLLLRRLRRLLLRRLLRLLLRRLRRLLRRRLLRLLRRRLRRLLLRRLLRLLRRRLRRLLRRRLLRLLLRRLRRLLLRRLLRLLRRRLRRLLRRRLLRLLRRRLRRLLLRRLLRLLLRRLRRLLRRRLLRLLLRRLRRLLLRRLLRLLLRRLRRLLRRRLLRLLRRRLRRLLLRRLLRLLRRRLRRLLRRRLLRLLLRRLRRLLLRRLLRLLLRRLRRLLRRRLLRLLRRRLRRLLLRRLLRLLLRRLRRLLRRRLLRLLLRRLRRLLLRRLLRLLRRRLRRLLRRRLLRLLRRRLRRLLLRRLLRLLRRRLRRLLRRRLLRLLLRRLRRLLLRRLLRLLRRRLRRLLRRRLLRLLRRRLRRLLLRRLLRLLLRRLRRLLRRRLLRLLLRRLRRLLLRRLLRLLRRRLRRLLRRRLLRLLRRRLRRLLLRRLLRLLRRRLRRLLRRRLLRLLLRRLRRLLLRRLLRLLLRRLRRLLRRRLLRLLRRRLRRLLLRRLLRLLLRRLRRLLRRRLLRLLLRRLRRLLLRRLLRLLRRRLRRLLRRRLLRLLRRRLRRLLLRRLLRLLRRRLRRLLRRRLLRLLLRRLRRLLLRRLLRLLRRRLRRLLRRRLLRLLRRRLRRLLLRRLLRLLLRRLRRLLRRRLLRLLLRRLRRLLLRRLLRLLLRRLRRLLRRRLLRLLRRRLRRLLLRRLLRLLRRRLRRLLRRRLLRLLLRRLRRLLLRRLLRLLLRRLRRLLRRRLLRLLRRRLRRLLLRRLLRLLLRRLRRLLRRRLLRLLLRRLRRLLLRRLLRLLLRRLRRLLRRRLLRLLRRRLRRLLLRRLLRLLRRRLRRLLRRRLLRLLLRRLRRLLLRRLLRLLRRRLRRLLRRRLLRLLRRRLRRLLLRRLLRLLLRRLRRLLRRRLLRLLLRRLRRLLLRRLLRLLRRRLRRLLRRRLLRLLRRRLRRLLLRRLLRLLRRRLRRLLRRRLLRLLLRRLRRLLLRRLLRLLLRRLRRLLRRRLLRLLRRRLRRLLLRRLLRLLLRRLRRLLRRRLLRLLLRRLRRLLLRRLLRLLLRRLRRLLRRRLLRLLRRRLRRLLLRRLLRLLRRRLRRLLRRRLLRLLLRRLRRLLLRRLLRLLRRRLRRLLRRRLLRLLRRRLRRLLLRRLLRLLLRRLRRLLRRRLLRLLLRRLRRLLLRRLLRLLLRRLRRLLRRRLLRLLRRRLRRLLLRRLLRLLRRRLRRLLRRRLLRLLLRRLRRLLLRRLLRLLLRRLRRLLRRRLLRLLRRRLRRLLLRRLLRLLLRRLRRLLRRRLLRLLLRRLRRLLLRRLLRLLRRRLRRLLRRRLLRLLRRRLRRLLLRRLLRLLRRRLRRLLRRRLLRLLLRRLRRLLLRRLLRLLRRRLRRLLRRRLLRLLRRRLRRLLLRRLLRLLLRRLRRLLRRRLLRLLLRRLRRLLLRRLLRLLRRRLRRLLRRRLLRLLRRRLRRLLLRRLLRLLRRRLRRLLRRRLLRLLLRRLRRLLLRRLLRLLLRRLRRLLRRRLLRLLRRRLRRLLLRRLLRLLLRRLRRLLRRRLLRLLLRRLRRLLLRRLLRLLRRRLRRLLRRRLLRLLRRRLRRLLLRRLLRLLRRRLRRLLRRRLLRLLLRRLRRLLLRRLLRLLRRRLRRLLRRRLLRLLRRRLRRLLLRRLLRLLLRRLRRLLRRRLLRLLLRRLRRLLLRRLLRLLLRRLRRLLRRRLLRLLRRRLRRLLLRRLLRLLRRRLRRLLRRRLLRLLLRRLRRLLLRRLLRLLLRRLRRLLRRRLLRLLRRRLRRLLLRRLLRLLLRRLRRLLRRRLLRLLLRRLRRLLLRRLLRLLRRRLRRLLRRRLLRLLRRRLRRLLLRRLLRLLRRRLRRLLRRRLLRLLLRRLRRLLLRRLLRLLRRRLRRLLRRRLLRLLRRRLRRLLLRRLLRLLLRRLRRLLRRRLLRLLLRRLRRLLLRRLLRLLRRRLRRLLRRRLLRLLRRRLRRLLLRRLLRLLRRRLRRLLRRRLLRLLLRRLRRLLLRRLLRLLLRRLRRLLRRRLLRLLRRRLRRLLLRRLLRLLLRRLRRLLRRRLLRLLLRRLRRLLLRRLLRLLLRRLRRLLRRRLLRLLRRRLRRLLLRRLLRLLRRRLRRLLRRRLLRLLLRRLRRLLLRRLLRLLRRRLRRLLRRRLLRLLRRRLRRLLLRRLLRLLLRRLRRLLRRRLLRLLLRRLRRLLLRRLLRLLLRRLRRLLRRRLLRLLRRRLRRLLLRRLLRLLRRRLRRLLRRRLLRLLLRRLRRLLLRRLLRLLLRRLRRLLRRRLLRLLRRRLRRLLLRRLLRLLLRRLRRLLRRRLLRLLLRRLRRLLLRRLLRLLLRRLRRLLRRRLLRLLRRRLRRLLLRRLLRLLRRRLRRLLRRRLLRLLLRRLRRLLLRRLLRLLRRRLRRLLRRRLLRLLRRRLRRLLLRRLLRLLLRRLRRLLRRRLLRLLLRRLRRLLLRRLLRLLRRRLRRLLRRRLLRLLRRRLRRLLLRRLLRLLRRRLRRLLRRRLLRLLLRRLRRLLLRRLLRLLLRRLRRLLRRRLLRLLRRRLRRLLLRRLLRLLLRRLRRLLRRRLLRLLLRRLRRLLLRRLLRLLRRRLRRLLRRRLLRLLRRRLRRLLLRRLLRLLRRRLRRLLRRRLLRLLLRRLRRLLLRRLLRLLRRRLRRLLRRRLLRLLRRRLRRLLLRRLLRLLLRRLRRLLRRRLLRLLLRRLRRLLLRRLLRLLLRRLRRLLRRRLLRLLRRRLRRLLLRRLLRLLRRRLRRLLRRRLLRLLLRRLRRLLLRRLLRLLLRRLRRLLRRRLLRLLRRRLRRLLLRRLLRLLLRRLRRLLRRRLLRLLLRRLRRLLLRRLLRLLLRRLRRLLRRRLLRLLRRRLRRLLLRRLLRLLRRRLRRLLRRRLLRLLLRRLRRLLLRRLLRLLRRRLRRLLRRRLLRLLRRRLRRLLLRRLLRLLLRRLRRLLRRRLLRLLLRRLRRLLLRRLLRLLRRRLRRLLRRRLLRLLRRRLRRLLLRRLLRLLRRRLRRLLRRRLLRLLLRRLRRLLLRRLLRLLLRRLRRLLRRRLLRLLRRRLRRLLLRRLLRLLLRRLRRLLRRRLLRLLLRRLRRLLLRRLLRLLLRRLRRLLRRRLLRLLRRRLRRLLLRRLLRLLRRRLRRLLRRRLLRLLLRRLRRLLLRRLLRLLRRRLRRLLRRRLLRLLRRRLRRLLLRRLLRLLLRRLRRLLRRRLLRLLLRRLRRLLLRRLLRLLLRRLRRLLRRRLLRLLRRRLRRLLLRRLLRLLRRRLRRLLRRRLLRLLLRRLRRLLLRRLLRLLLRRLRRLLRRRLLRLLRRRLRRLLLRRLLRLLLRRLRRLLRRRLLRLLLRRLRRLLLRRLLRLLLRRLRRLLRRRLLRLLRRRLRRLLLRRLLRLLRRRLRRLLRRRLLRLLLRRLRRLLLRRLLRLLRRRLRRLLRRRLLRLLRRRLRRLLLRRLLRLLLRRLRRLLRRRLLRLLLRRLRRLLLRRLLRLLRRRLRRLLRRRLLRLLRRRLRRLLLRRLLRLLRRRLRRLLRRRLLRLLLRRLRRLLLRRLLRLLLRRLRRLLRRRLLRLLRRRLRRLLLRRLLRLLLRRLRRLLRRRLLRLLLRRLRRLLLRRLLRLLRRRLRRLLRRRLLRLLRRRLRRLLLRRLLRLLRRRLRRLLRRRLLRLLLRRLRRLLLRRLLRLLRRRLRRLLRRRLLRLLRRRLRRLLLRRLLRLLLRRLRRLLRRRLLRLLLRRLRRLLLRRLLRLLLRRLRRLLRRRLLRLLRRRLRRLLLRRLLRLLRRRLRRLLRRRLLRLLLRRLRRLLLRRLLRLLLRRLRRLLRRRLLRLLRRRLRRLLLRRLLRLLLRRLRRLLRRRLLRLLLRRLRRLLLRRLLRLLRRRLRRLLRRRLLRLLRRRLRRLLLRRLLRLLRRRLRRLLRRRLLRLLLRRLRRLLLRRLLRLLRRRLRRLLRRRLLRLLRRRLRRLLLRRLLRLLLRRLRRLLRRRLLRLLLRRLRRLLLRRLLRLLRRRLRRLLRRRLLRLLRRRLRRLLLRRLLRLLRRRLRRLLRRRLLRLLLRRLRRLLLRRLLRLLLRRLRRLLRRRLLRLLRRRLRRLLLRRLLRLLLRRLRRLLRRRLLRLLLRRLRRLLLRRLLRLLLRRLRRLLRRRLLRLLRRRLRRLLLRRLLRLLRRRLRRLLRRRLLRLLLRRLRRLLLRRLLRLLRRRLRRLLRRRLLRLLRRRLRRLLLRRLLRLLLRRLRRLLRRRLLRLLLRRLRRLLLRRLLRLLLRRLRRLLRRRLLRLLRRRLRRLLLRRLLRLLRRRLRRLLRRRLLRLLLRRLRRLLLRRLLRLLLRRLRRLLRRRLLRLLRRRLRRLLLRRLLRLLLRRLRRLLRRRLLRLLLRRLRRLLLRRLLRLLRRRLRRLLRRRLLRLLRRRLRRLLLRRLLRLLRRRLRRLLRRRLLRLLLRRLRRLLLRRLLRLLRRRLRRLLRRRLLRLLRRRLRRLLLRRLLRLLLRRLRRLLRRRLLRLLLRRLRRLLLRRLLRLLRRRLRRLLRRRLLRLLRRRLRRLLLRRLLRLLRRRLRRLLRRRLLRLLLRRLRRLLLRRLLRLLLRRLRRLLRRRLLRLLRRRLRRLLLRRLLRLLLRRLRRLLRRRLLRLLLRRLRRLLLRRLLRLLRRRLRRLLRRRLLRLLRRRLRRLLLRRLLRLLRRRLRRLLRRRLLRLLLRRLRRLLLRRLLRLLRRRLRRLLRRRLLRLLRRRLRRLLLRRLLRLLLRRLRRLLRRRLLRLLLRRLRRLLLRRLLRLLLRRLRRLLRRRLLRLLRRRLRRLLLRRLLRLLRRRLRRLLRRRLLRLLLRRLRRLLLRRLLRLLLRRLRRLLRRRLLRLLRRRLRRLLLRRLLRLLLRRLRRLLRRRLLRLLLRRLRRLLLRRLLRLLLRRLRRLLRRRLLRLLRRRLRRLLLRRLLRLLRRRLRRLLRRRLLRLLLRRLRRLLLRRLLRLLRRRLRRLLRRRLLRLLRRRLRRLLLRRLLRLLLRRLRRLLRRRLLRLLLRRLRRLLLRRLLRLLRRRLRRLLRRRLLRLLRRRLRRLLLRRLLRLLRRRLRRLLRRRLLRLLLRRLRRLLLRRLLRLLLRRLRRLLRRRLLRLLRRRLRRLLLRRLLRLLLRRLRRLLRRRLLRLLLRRLRRLLLRRLLRLLLRRLRRLLRRRLLRLLRRRLRRLLLRRLLRLLRRRLRRLLRRRLLRLLLRRLRRLLLRRLLRLLRRRLRRLLRRRLLRLLRRRLRRLLLRRLLRLLLRRLRRLLRRRLLRLLLRRLRRLLLRRLLRLLLRRLRRLLRRRLLRLLRRRLRRLLLRRLLRLLRRRLRRLLRRRLLRLLLRRLRRLLLRRLLRLLLRRLRRLLRRRLLRLLRRRLRRLLLRRLLRLLLRRLRRLLRRRLLRLLLRRLRRLLLRRLLRLLLRRLRRLLRRRLLRLLRRRLRRLLLRRLLRLLRRRLRRLLRRRLLRLLLRRLRRLLLRRLLRLLRRRLRRLLRRRLLRLLRRRLRRLLLRRLLRLLLRRLRRLLRRRLLRLLLRRLRRLLLRRLLRLLRRRLRRLLRRRLLRLLRRRLRRLLLRRLLRLLRRRLRRLLRRRLLRLLLRRLRRLLLRRLLRLLLRRLRRLLRRRLLRLLRRRLRRLLLRRLLRLLLRRLRRLLRRRLLRLLLRRLRRLLLRRLLRLLRRRLRRLLRRRLLRLLRRRLRRLLLRRLLRLLRRRLRRLLRRRLLRLLLRRLRRLLLRRLLRLLRRRLRRLLRRRLLRLLRRRLRRLLLRRLLRLLLRRLRRLLRRRLLRLLLRRLRRLLLRRLLRLLLRRLRRLLRRRLLRLLRRRLRRLLLRRLLRLLRRRLRRLLRRRLLRLLLRRLRRLLLRRLLRLLLRRLRRLLRRRLLRLLRRRLRRLLLRRLLRLLLRRLRRLLRRRLLRLLLRRLRRLLLRRLLRLLRRRLRRLLRRRLLRLLRRRLRRLLLRRLLRLLRRRLRRLLRRRLLRLLLRRLRRLLLRRLLRLLRRRLRRLLRRRLLRLLRRRLRRLLLRRLLRLLLRRLRRLLRRRLLRLLLRRLRRLLLRRLLRLLRRRLRRLLRRRLLRLLRRRLRRLLLRRLLRLLRRRLRRLLRRRLLRLLLRRLRRLLLRRLLRLLLRRLRRLLRRRLLRLLRRRLRRLLLRRLLRLLLRRLRRLLRRRLLRLLLRRLRRLLLRRLLRLLLRRLRRLLRRRLLRLLRRRLRRLLLRRLLRLLRRRLRRLLRRRLLRLLLRRLRRLLLRRLLRLLRRRLRRLLRRRLLRLLRRRLRRLLLRRLLRLLLRRLRRLLRRRLLRLLLRRLRRLLLRRLLRLLLRRLRRLLRRRLLRLLRRRLRRLLLRRLLRLLRRRLRRLLRRRLLRLLLRRLRRLLLRRLLRLLLRRLRRLLRRRLLRLLRRRLRRLLLRRLLRLLLRRLRRLLRRRLLRLLLRRLRRLLLRRLLRLLLRRLRRLLRRRLLRLLRRRLRRLLLRRLLRLLRRRLRRLLRRRLLRLLLRRLRRLLLRRLLRLLRRRLRRLLRRRLLRLLRRRLRRLLLRRLLRLLLRRLRRLLRRRLLRLLLRRLRRLLLRRLLRLLRRRLRRLLRRRLLRLLRRRLRRLLLRRLLRLLRRRLRRLLRRRLLRLLLRRLRRLLLRRLLRLLLRRLRRLLRRRLLRLLRRRLRRLLLRRLLRLLLRRLRRLLRRRLLRLLLRRLRRLLLRRLLRLLRRRLRRLLRRRLLRLLRRRLRRLLLRRLLRLLRRRLRRLLRRRLLRLLLRRLRRLLLRRLLRLLRRRLRRLLRRRLLRLLRRRLRRLLLRRLLRLLLRRLRRLLRRRLLRLLLRRLRRLLLRRLLRLLLRRLRRLLRRRLLRLLRRRLRRLLLRRLLRLLRRRLRRLLRRRLLRLLLRRLRRLLLRRLLRLLLRRLRRLLRRRLLRLLRRRLRRLLLRRLLRLLLRRLRRLLRRRLLRLLLRRLRRLLLRRLLRLLLRRLRRLLRRRLLRLLRRRLRRLLLRRLLRLLRRRLRRLLRRRLLRLLLRRLRRLLLRRLLRLLRRRLRRLLRRRLLRLLRRRLRRLLLRRLLRLLLRRLRRLLRRRLLRLLLRRLRRLLLRRLLRLLRRRLRRLLRRRLLRLLRRRLRRLLLRRLLRLLRRRLRRLLRRRLLRLLLRRLRRLLLRRLLRLLLRRLRRLLRRRLLRLLRRRLRRLLLRRLLRLLLRRLRRLLRRRLLRLLLRRLRRLLLRRLLRLLLRRLRRLLRRRLLRLLRRRLRRLLLRRLLRLLRRRLRRLLRRRLLRLLLRRLRRLLLRRLLRLLRRRLRRLLRRRLLRLLRRRLRRLLLRRLLRLLLRRLRRLLRRRLLRLLLRRLRRLLLRRLLRLLLRRLRRLLRRRLLRLLRRRLRRLLLRRLLRLLRRRLRRLLRRRLLRLLLRRLRRLLLRRLLRLLLRRLRRLLRRRLLRLLRRRLRRLLLRRLLRLLLRRLRRLLRRRLLRLLLRRLRRLLLRRLLRLL"
    }

    def "11: gray code tests"() {
        given:
        def result = StringTasks.makeGrayCode(n)

        expect:
        result == expectedResult

        where:
        n || expectedResult
        0 || "0"
        1 || "0 1 0"
        2 || "0 1 0 2 0 1 0"
        3 || "0 1 0 2 0 1 0 3 0 1 0 2 0 1 0"
    }


}
